disabled = false
locale = "en"
label = "English"
weight = 1
title = "Shen Milan"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Systems & Infrastructure Engineer"
  copyright = "© 2026 Shen Milan"

[params.author]
  name = "Shen Milan"
  headline = "Systems & Infrastructure Engineer"
  bio = "Homelab enthusiast building highly secure infrastructure architectures, networks, and automated pipeline environments."
  links = [
    { github = "https://github.com/shen-nm" },
    { linkedin = "https://www.linkedin.com/in/jhenrick-shen-milan-b7b91a249/" },
  ]